trainer:
  _target_: pytorch_lightning.Trainer

  max_steps: 50000
  max_epochs: -1
  
  log_every_n_steps: 500
  check_val_every_n_epoch: 10  # <--- Valida ogni 10 epochs (~1,620 steps con bs=128)
  num_sanity_val_steps: 0
  
  accelerator: gpu
  devices: 1

  # logger: false  # <--- AGGIUNGI QUESTA RIGA

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${run_dir}/checkpoints
      filename: 'step_{step:06d}'
      every_n_train_steps: 10000
      save_top_k: -1
      save_last: true
      
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${run_dir}/checkpoints
      filename: 'best'
      save_top_k: 1
      monitor: val/loss
      mode: min
      
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
      
    - _target_: src.callback.progress.ProgressLogger
      precision: 3
      # log_every_n_steps: 2  # <--- Aggiungi questo parametro
      
    - _target_: src.callback.tqdmbar.TQDMProgressBar
