
HYDRA_FULL_ERROR=1 python train_model_spo.py \
    data=humanml3d \
    model=mdm_spo \
    data.with_noise=false \
    data.text_to_token_emb=false \
    data.text_to_sent_emb=false \
    dataloader.batch_size=256 \
    model.train_batch_size=256 \
    model.lr=1e-7 \
    model.ckpt="last" \
    evaluator.checkpoint_dir='outputs/densetmr_humanml3d_smplrifke' \
    model.checkpoint_dir='outputs/mdm_kitml_smplrifke' \
    run_dir='outputs/mdmspo_kitml_to_humanml3d_smplrifke_lr1e-7_bs256' \
    trainer.max_epochs=20 \
    group_name='K2H' 

HYDRA_FULL_ERROR=1 python train_model_spo.py \
    data=babel \
    model=mdm_spo \
    data.with_noise=false \
    data.text_to_token_emb=false \
    data.text_to_sent_emb=false \
    dataloader.batch_size=256 \
    model.train_batch_size=256 \
    model.lr=1e-7 \
    model.ckpt="last" \
    evaluator.checkpoint_dir='outputs/densetmr_babel_smplrifke' \
    model.checkpoint_dir='outputs/mdm_kitml_smplrifke' \
    run_dir='outputs/mdmspo_kitml_to_babel_smplrifke_lr1e-7_bs256' \
    trainer.max_epochs=20 \
    group_name='K2B' 

HYDRA_FULL_ERROR=1 python train_model_spo.py \
    data=motionx \
    model=mdm_spo \
    data.with_noise=false \
    data.text_to_token_emb=false \
    data.text_to_sent_emb=false \
    dataloader.batch_size=256 \
    model.train_batch_size=256 \
    model.lr=1e-7 \
    model.ckpt="last" \
    evaluator.checkpoint_dir='outputs/densetmr_motionx_smplrifke' \
    model.checkpoint_dir='outputs/mdm_kitml_smplrifke' \
    run_dir='outputs/mdmspo_kitml_to_motionx_smplrifke_lr1e-7_bs256' \
    trainer.max_epochs=20 \
    group_name='K2M' 
